### ISSUE TITLE
can not identify the hole and evenly fill the whole model

### ISSUE THREAD

**Issue by ScarlettLeong** [Geodan/fill-holes-pointcloud#2]
hi,I have some problems when test the project,it can not identify the hole,and fill the whole model with synthetic points,so the project can not work yet?Or I didn't do on the right way?I use .pts point cloud,thank you.

**Comment by chrislcs** [comment]
Could you show me the code you use to run the script? I currently have too little information to determine what the problem is.

**Comment by ScarlettLeong** [comment]
`fill_points_1 = fill_holes(points, 0.0001, 0.001, percentile=50)`
`points`is a (x,y,z) list read from pts file like
[[-12.45945   9.81175 -28.5556 ]
 [-12.49045   9.91075 -28.2966 ]
 [-12.48745   9.89875 -28.3256 ]
 ...
 [-12.71245  10.74975 -29.6816]
 [-12.78645  11.01675 -30.0306 ]
 [-12.66745  10.55475 -29.3636]]
but the project can't find the hole but fill the whole model

**Comment by chrislcs** [comment]
Your values for `max_circumradius` and `max_ratio_radius_area ` are probably too small. It now sees a triangle with a circumradius bigger than 0.0001 and with a ratio between that radius and the area of 0.001 as a hole. Given that these values are so small it probably sees all triangles as holes and thus fills everything with points. Try using more sensible values for these two parameters. This is dependent on the distance between the points in your point cloud. You will have to find reasonable values yourself.
